import { Component, OnInit, ViewChild } from "@angular/core";
import { MatPaginator, MatSort, MatTableDataSource } from "@angular/material";
import { CompanyClient, GetCompanyDto } from "src/app/autogenerated/api";

@Component({
  selector: "app-tenant",
  templateUrl: "./tenant.component.html",
  styleUrls: ["./tenant.component.css"],
})
export class TenantComponent implements OnInit {
  dataSource: MatTableDataSource<GetCompanyDto>;
  tenants: GetCompanyDto[];
  columns: string[] = ["id", "companyName","fiscalCode", "fiscalAttribute", "recomNumber", "address", "actions"];

  @ViewChild(MatSort, { static: true }) sort: MatSort;
  @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;

  constructor(private tenantClient: CompanyClient) {}

  ngOnInit() {
    this.tenantClient.listCompanies().subscribe((result) => {
      this.tenants = result;
      this.dataSource = new MatTableDataSource(this.tenants);
      this.dataSource.paginator = this.paginator;
      this.dataSource.sort = this.sort;
    });
  }
  applyFilter(event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();
    this.paginator.firstPage();
  }
}
