import { Component, OnInit } from '@angular/core';
import { CenterClient } from 'src/app/autogenerated/api';
import {GetCenterDto} from 'src/app/autogenerated/api';


@Component({
  selector: 'app-center',
  templateUrl: './center.component.html',
  styleUrls: ['./center.component.css']
})
export class CenterComponent implements OnInit  {

  centers: GetCenterDto[]=[];
  
  constructor(private readonly centerClient:CenterClient) { }

  ngOnInit(){

   this.centerClient.listCenters().subscribe(data => {
      this.centers=data;
  });
  }

}
