import { Component, OnInit } from "@angular/core";
import { CenterClient } from "src/app/autogenerated/api";
import { GetUnitDto } from "src/app/autogenerated/api";
import { ActivatedRoute, Router } from "@angular/router";
import { MatTableDataSource } from "@angular/material/table";
import {UnitsDataSource} from "./units.datasource";

@Component({
  selector: "app-unit",
  templateUrl: "./unit.component.html",
  styleUrls: ["./unit.component.css"],
})
export class UnitComponent implements OnInit {
  // dataSource: MatTableDataSource<GetUnitDto>;
  columnsToDisplay = ["id"];
  units: UnitsDataSource;
  id: number;
  constructor(
    private readonly centerClient: CenterClient,
    private route: ActivatedRoute,
    private router: Router
  ) {
    
  }

  ngOnInit() {
    this.id = parseInt(this.route.snapshot.paramMap.get("id"));
    const units$ = this.centerClient.listUnitsInCenter(this.id)
    // this.units = new UnitsDataSource(units$);
   
  }
}
//applyFilter(event: Event) {
//  const filterValue = (event.target as HTMLInputElement).value;
//  this.dataSource.filter = filterValue.trim().toLowerCase();
//}
