import { Component, OnInit } from "@angular/core";
import { CenterClient, GetCenterDto } from "src/app/autogenerated/api";
import { GetUnitDto } from "src/app/autogenerated/api";
import { ActivatedRoute, Router } from "@angular/router";
import { UnitsDataSource } from "./units.datasource";
import { MatDialog } from "@angular/material";
import { LeaseViewComponent } from "src/app/leases/lease-view/lease-view.component";

@Component({
  selector: "app-unit",
  templateUrl: "./unit.component.html",
  styleUrls: ["./unit.component.css"],
})
export class UnitComponent implements OnInit {
  dataSource: UnitsDataSource;
  center: GetCenterDto;
  displayedColumns = ["id", "unitCode", "area", "floor", "type",  "monthlyRentSqm", 
  "monthlyMaintenanceCostSqm","monthlyMarketingFeeSqm", "actions"];
   id: number;
   unitId:number;


  constructor(
    private readonly centerClient: CenterClient,
    private route: ActivatedRoute,  
    private router: Router,
    public dialog: MatDialog
  ) {}

  ngOnInit() {
    this.id = parseInt(this.route.snapshot.paramMap.get("id"));
    // this.unitId=parseInt(this.route.snapshot.paramMap.get("unitId"));

   this.centerClient.getCenterById(this.id).subscribe(data=>this.center=data);
    this.dataSource = new UnitsDataSource(this.centerClient);
  
    this.dataSource.loadUnits(this.id);

  }
  openDialog(id:number) {

    this.unitId=id;
    const dialogRef = this.dialog.open(LeaseViewComponent);


    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog result: ${result}`);
    });
  }



  onRowClicked(row) {
    console.log('Row clicked: ', row);
}



}