import { MatTableDataSource } from "@angular/material/table";
import { Observable, Subscription } from "rxjs";

import { GetUnitDto } from "src/app/autogenerated/api";


export class UnitsDataSource extends MatTableDataSource<GetUnitDto> {
  private transactions: GetUnitDto[] = [];

  private transactions$: Subscription;

  constructor(transactions: Observable<GetUnitDto>) {
    super();
    this.transactions$ = transactions.subscribe(transactionList => {
      this.transactions.push(transactionList);
      this.data = this.transactions;
    });
  }

  disconnect() {
    this.transactions$.unsubscribe();
    super.disconnect();
  }
}
